// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameContenedor = "contenedor"

// Contenedor mapped from table <contenedor>
type Contenedor struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Nombre string `gorm:"column:nombre;not null" json:"nombre"`
}

// TableName Contenedor's table name
func (*Contenedor) TableName() string {
	return TableNameContenedor
}
