// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHistorial = "historial"

// Historial mapped from table <historial>
type Historial struct {
	ID               int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Fecha            time.Time `gorm:"column:fecha;not null" json:"fecha"`
	Cantidad         int32     `gorm:"column:cantidad;not null" json:"cantidad"`
	Tipo             string    `gorm:"column:tipo;not null" json:"tipo"`
	NombreProducto   string    `gorm:"column:nombre_producto;not null" json:"nombre_producto"`
	NombreContenedor string    `gorm:"column:nombre_contenedor;not null" json:"nombre_contenedor"`
	ContenedorID     int32     `gorm:"column:contenedor_id" json:"contenedor_id"`
}

// TableName Historial's table name
func (*Historial) TableName() string {
	return TableNameHistorial
}
